[package]
name = "counter"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.1"
borsh-derive = "1.5.1"
solana-program = "2.0.1"

[dev-dependencies]
solana-program-test = "2.0.1"
solana-sdk = "2.0.1"
